### PR TITLE
quizCollections

### PR DESCRIPTION
**Pull request by upluke**
Hi, I "linked" some components so I ( and we) could test on it. They are removable if its necessary.

### CODE REVIEW

**Review by GreatDeveloper66 — COMMENTED** [review]
In the console, I got an error and warning. 

Error: Each child in a list should have a unique 'key' prop.

Warning: header is defined but never used. footer is defined but never used. AppCore is defined but never used.
If we aren't going to use these components any more go ahead and delete them.

**Comment by upluke** [comment]
Eliminated error. For unused components, because we haven't touched them.

**Review by saltamay — CHANGES_REQUESTED** [review]
Great looking cards. Just a few notes about styling:
- The glow is little too much on hover
- We should use either Flexbox or CSS Grid as opposed to hard-coding the pixels
- We can use max-height and max-width for the max height and width
- I think state should come from a js file that stores meta info about the quizzes
- style={{display: flex}} should move to styles file
- Instead of naming quiz info the state, we can use quizData and while mapping just quiz for more readable code

**Comment by upluke** [comment]
Removed the glow; changed px to %, rem and em; removed state and imported data from a js file; But there is still one inline `style` can't remove it. Plz let me know if you have any further suggestion, thanks for reviewing

**Review by saltamay — APPROVED** [review]
Great! I added a few changes to the quiz styles and got rid of the redundant code.  It's not fully responsive at the moment but great starting point

**Review by GreatDeveloper66 — APPROVED** [review]
I ran the app. It's working fine.

**Pull request merged**
