### PR TITLE
updateQuiz&Mul

### PR DESCRIPTION
**Pull request by upluke**

### CODE REVIEW

**Comment by saltamay** [comment]
I like the way you have implemented your logic, and your code style has improved significantly. A few things I'd like to point out are:
1. Instead of using a mock quiz, we can use the quiz.json to work with real data
2. Instead of hard coding the multiple choices, we should have a MultpleChoiceItem component that is rendered by the MultipleChoice component dynamically since we don't always know how many choices the question has.
3. You can group the radio buttons with the name attribute, so you don't have to set checked to true every time the radio button is checked
4. Most of your logic is handled on the Quiz component; you only need to pass 2 props to the MultipleChoiceItems that are choices and id.

**Review by saltamay — CHANGES_REQUESTED** [review]
I like the way you have implemented your logic, and your code style has improved significantly. A few things I'd like to point out are:

- Instead of using a mock quiz, we can use the quiz.json to work with real data
- Instead of hard coding the multiple choices, we should have a MultpleChoiceItem component that is rendered by the MultipleChoice component dynamically since we don't always know how many choices the question has.
- You can group the radio buttons with the name attribute, so you don't have to set checked to true every time the radio button is checked
- Most of your logic is handled on the Quiz component; you only need to pass 2 props to the MultipleChoiceItems that are choices and id.

**Comment by upluke** [comment]
Hi! Please review the changes

**Review by saltamay — CHANGES_REQUESTED** [review]
Hi,
- Code works, great job!
- I think we should get rid of the previous button cause once the user submitted their response they are graded, so no need for going back. And once previous pressed, the code breaks in terms of functionality.
-  I like the new questions. I would add them to the quiz.json file with the other questions and have it set up in a way that we have 2 different quizzes. (this could be an issue itself)
- With handleClickNext, you keep track of count on the parent component, however, you are passing the 'count' argument to the handleCheck to update the checkedOption property. You can just use the count hook for that.
- If you bundle the radio buttons with name, there is no need to keep track of checkedOption
- You can have currentQuestion hook that is used to keep track the current question, so you don't need to update the state with the whole questions array everytime next is clicked. 
- On MultipleChoices instead of having 2 return statements, I would combine everything into one

**Comment by upluke** [comment]
Hi, please review the changes.

**Review by saltamay — APPROVED** [review]
Great job! Thank you

**Pull request merged**
