### PR TITLE
chore: Add views folder with App components

### PR DESCRIPTION
**Pull request by saltamay**

### CODE REVIEW

**Comment by upluke** [comment]
OK

**Review by GreatDeveloper66 — COMMENTED** [review]
I ran into a problem. I pulled the branch to the local machine and tried to start the app. It failed to compile. I got the message: Can't resolve './App' in '.../src'. Could you doublecheck to import directory?

**Comment by saltamay** [comment]
Fixed file paths' of import statements

**Review by GreatDeveloper66 — APPROVED** [review]
It works now.

**Pull request merged**
